# Context

**The file I chose to use is the music by Alicia keys new york.**

**Use Recurring Neural Networks to generate texts.**

**The Neural Network will learn from the texts so that it can write its own texts.**




In [1]:
import tensorflow as tf
import numpy as np
import os
import time
import pandas as pd

In [ ]:
!unzip "/content/archive.zip"

# Database loading and exploration

In [5]:
data = '/content/alicia-keys.txt'

In [6]:
dataset_text = open(data, 'rb').read().decode(encoding = 'utf-8')

In [ ]:
print(dataset_text)

In [8]:
len(dataset_text)

113439

In [9]:
vocab = sorted(set(dataset_text))

In [10]:
print('{} unique characters'.format(len(vocab)))

76 unique characters


In [11]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '4',
 '6',
 '8',
 '9',
 ':',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'Y',
 '[',
 ']',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '¢',
 'Ã',
 'é',
 'ó',
 'ú']

# Mapping text to numbers

In [12]:
char2idx = {char: index for index, char in enumerate(vocab)}

In [13]:
char2idx

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '4': 14,
 '6': 15,
 '8': 16,
 '9': 17,
 ':': 18,
 '?': 19,
 'A': 20,
 'B': 21,
 'C': 22,
 'D': 23,
 'E': 24,
 'F': 25,
 'G': 26,
 'H': 27,
 'I': 28,
 'J': 29,
 'K': 30,
 'L': 31,
 'M': 32,
 'N': 33,
 'O': 34,
 'P': 35,
 'R': 36,
 'S': 37,
 'T': 38,
 'U': 39,
 'V': 40,
 'W': 41,
 'Y': 42,
 '[': 43,
 ']': 44,
 'a': 45,
 'b': 46,
 'c': 47,
 'd': 48,
 'e': 49,
 'f': 50,
 'g': 51,
 'h': 52,
 'i': 53,
 'j': 54,
 'k': 55,
 'l': 56,
 'm': 57,
 'n': 58,
 'o': 59,
 'p': 60,
 'q': 61,
 'r': 62,
 's': 63,
 't': 64,
 'u': 65,
 'v': 66,
 'w': 67,
 'x': 68,
 'y': 69,
 'z': 70,
 '¢': 71,
 'Ã': 72,
 'é': 73,
 'ó': 74,
 'ú': 75}

In [14]:
idx2char = np.array(vocab)

In [15]:
idx2char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '4', '6', '8', '9', ':', '?', 'A', 'B', 'C', 'D', 'E', 'F',
       'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T',
       'U', 'V', 'W', 'Y', '[', ']', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
       'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', '¢', 'Ã', 'é', 'ó', 'ú'], dtype='<U1')

In [16]:
idx2char[10]

'.'

In [17]:
char2idx[':']

18

In [18]:
text_as_int = np.array([char2idx[char] for char in dataset_text])

In [19]:
text_as_int

array([34, 59, 52, ..., 64, 63,  1])

In [20]:
text_as_int.shape

(113439,)

In [21]:
print('{} characters mapped to int ---> {}'.format(repr(dataset_text[:13]), text_as_int[:13]))

'Ooh....... Ne' characters mapped to int ---> [34 59 52 10 10 10 10 10 10 10  1 33 49]


# Creation of training examples and batches

In [22]:
len(dataset_text)

113439

In [23]:
seq_length = 100
examples_per_epoch = len(dataset_text) // seq_length
examples_per_epoch

1134

In [24]:
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

In [25]:
char_dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [26]:
sequences = char_dataset.batch(seq_length + 1, drop_remainder=True)

In [27]:
sequences

<BatchDataset element_spec=TensorSpec(shape=(101,), dtype=tf.int64, name=None)>

In [28]:
for item in sequences.take(50):
  print(repr(''.join(idx2char[item.numpy()])))

'Ooh....... New York x2 Grew up in a town that is famous as a place of movie scenes\nNoise is always lo'
'ud, there are sirens all around and the streets are mean\nIf I can make it here, I can make it anywher'
"e, that's what they say\nSeeing my face in lights or my name on marquees found down on Broadway Even i"
"f it ain't all it seems, I got a pocket full of dreams\nBaby, I'm from New York\nConcrete jungle where "
"dreams are made of\nThere's nothing you can't do\nNow you're in New York\nThese streets will make you fe"
'el brand new\nBig lights will inspire you\nHear it from New York, New York, New York! On the avenue, th'
"ere ain't never a curfew, ladies work so hard\nSuch a melting pot, on the corner selling rock, preache"
'rs pray to God\nHail a gypsy-cab, takes me down from Harlem to the Brooklyn Bridge\nSome will sleep ton'
"ight with a hunger far more than an empty fridge I'm gonna make it by any means, I got a pocket full "
"of dreams\nBaby, I'm from New York\nConcrete jungl

In [29]:
def split_input_target(chunk):
  input_text = chunk[:-1]
  target_text = chunk[1:]
  return input_text, target_text

In [30]:
dataset = sequences.map(split_input_target)

In [31]:
for input_example, target_example in dataset.take(10):
  print('Input data:', repr(''.join(idx2char[input_example.numpy()])))
  print('Target data:', repr(''.join(idx2char[target_example.numpy()])))

Input data: 'Ooh....... New York x2 Grew up in a town that is famous as a place of movie scenes\nNoise is always l'
Target data: 'oh....... New York x2 Grew up in a town that is famous as a place of movie scenes\nNoise is always lo'
Input data: 'ud, there are sirens all around and the streets are mean\nIf I can make it here, I can make it anywhe'
Target data: 'd, there are sirens all around and the streets are mean\nIf I can make it here, I can make it anywher'
Input data: "e, that's what they say\nSeeing my face in lights or my name on marquees found down on Broadway Even "
Target data: ", that's what they say\nSeeing my face in lights or my name on marquees found down on Broadway Even i"
Input data: "f it ain't all it seems, I got a pocket full of dreams\nBaby, I'm from New York\nConcrete jungle where"
Target data: " it ain't all it seems, I got a pocket full of dreams\nBaby, I'm from New York\nConcrete jungle where "
Input data: "dreams are made of\nThere's nothing you can't do\nNow

In [32]:
batch_size = 64
buffer_size = 10000

In [33]:
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder = True)

In [34]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

# Model building

In [35]:
len(vocab)

76

In [36]:
vocab_size = len(vocab)

In [37]:
embedding_dim = 256

In [38]:
rnn_units = 1024

In [39]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([tf.keras.layers.Embedding(vocab_size, embedding_dim, batch_input_shape=[batch_size, None]),
                               tf.keras.layers.LSTM(rnn_units, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'),
                               tf.keras.layers.Dense(vocab_size)])
  return model

In [40]:
model = build_model(vocab_size = len(vocab), embedding_dim=embedding_dim, rnn_units=rnn_units, batch_size=batch_size)

In [41]:
for input_example_batch, target_example_batch in dataset.take(10):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape)

(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)
(64, 100, 76)


In [42]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [43]:
sampled_indices

<tf.Tensor: shape=(100, 1), dtype=int64, numpy=
array([[43],
       [65],
       [20],
       [ 7],
       [ 4],
       [72],
       [30],
       [ 8],
       [ 1],
       [24],
       [53],
       [46],
       [52],
       [ 9],
       [18],
       [49],
       [71],
       [16],
       [20],
       [56],
       [ 8],
       [50],
       [51],
       [27],
       [ 9],
       [45],
       [41],
       [67],
       [39],
       [62],
       [ 4],
       [ 6],
       [29],
       [14],
       [31],
       [40],
       [72],
       [ 6],
       [27],
       [56],
       [36],
       [ 4],
       [15],
       [53],
       [69],
       [42],
       [67],
       [41],
       [72],
       [43],
       [74],
       [40],
       [42],
       [22],
       [33],
       [28],
       [56],
       [37],
       [40],
       [60],
       [14],
       [60],
       [36],
       [60],
       [70],
       [ 8],
       [67],
       [32],
       [63],
       [47],
       [46],
       [12],
       [ 3],
   

In [44]:
sampled_indices = tf.squeeze(sampled_indices, axis = -1).numpy()

In [45]:
sampled_indices

array([43, 65, 20,  7,  4, 72, 30,  8,  1, 24, 53, 46, 52,  9, 18, 49, 71,
       16, 20, 56,  8, 50, 51, 27,  9, 45, 41, 67, 39, 62,  4,  6, 29, 14,
       31, 40, 72,  6, 27, 56, 36,  4, 15, 53, 69, 42, 67, 41, 72, 43, 74,
       40, 42, 22, 33, 28, 56, 37, 40, 60, 14, 60, 36, 60, 70,  8, 67, 32,
       63, 47, 46, 12,  3, 48, 50, 38, 74, 57,  0, 42, 69, 16, 16, 68, 16,
       56, 24, 67, 49, 41, 59, 40, 65, 42, 17, 25, 45, 12, 28,  2])

In [46]:
print('Input: \n', repr(''.join(idx2char[input_example_batch[0]])))
print()
print('Next char predictions: \n', repr(''.join(idx2char[sampled_indices])))

Input: 
 "n't wait, I don't wanna wait\nI can't wait, I can't wait, I won't wait, I don't wanna wait Oooh oooh,"

Next char predictions: 
 '[uA)&ÃK, Eibh-:e¢8Al,fgH-aWwUr&(J4LVÃ(HlR&6iyYwWÃ[óVYCNIlSVp4pRpz,wMscb1"dfTóm\nYy88x8lEweWoVuY9Fa1I!'


# Model training

**Optimizer and loss function**

In [47]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

In [48]:
example_batch_loss = loss(target_example_batch, example_batch_predictions)

In [49]:
example_batch_loss.numpy().mean()

4.330301

In [50]:
model.compile(optimizer='Adam', loss=loss)

**Checkpoints**

In [51]:
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt_{epoch}')
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix, save_weights_only=True)

# Execution of training

In [52]:
epochs = 40
history = model.fit(dataset, epochs = epochs, callbacks=[checkpoint_callback])

Epoch 1/40
17/17 [==============================] - 6s 177ms/step - loss: 3.3768
Epoch 2/40
17/17 [==============================] - 3s 163ms/step - loss: 3.0765
Epoch 3/40
17/17 [==============================] - 3s 163ms/step - loss: 2.8843
Epoch 4/40
17/17 [==============================] - 3s 165ms/step - loss: 2.5776
Epoch 5/40
17/17 [==============================] - 3s 166ms/step - loss: 2.3908
Epoch 6/40
17/17 [==============================] - 3s 167ms/step - loss: 2.2643
Epoch 7/40
17/17 [==============================] - 3s 165ms/step - loss: 2.1524
Epoch 8/40
17/17 [==============================] - 3s 165ms/step - loss: 2.0456
Epoch 9/40
17/17 [==============================] - 3s 166ms/step - loss: 1.9367
Epoch 10/40
17/17 [==============================] - 3s 168ms/step - loss: 1.8347
Epoch 11/40
17/17 [==============================] - 3s 173ms/step - loss: 1.7425
Epoch 12/40
17/17 [==============================] - 3s 168ms/step - loss: 1.6522
Epoch 13/40
17/17 [======

# Text Generation

Restore last checkpoint

In [53]:
tf.train.latest_checkpoint(checkpoint_dir)

'./training_checkpoints/ckpt_40'

In [54]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size = 1)
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1, None]))

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 256)            19456     
                                                                 
 lstm_1 (LSTM)               (1, None, 1024)           5246976   
                                                                 
 dense_1 (Dense)             (1, None, 76)             77900     
                                                                 
Total params: 5,344,332
Trainable params: 5,344,332
Non-trainable params: 0
_________________________________________________________________


# Prediction Loop

In [56]:
def generate_text(model, start_string):
  
  num_generate = 1000

  
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)
  
  text_generated = []
   
  temperature = 1.0

  
  for i in range(num_generate):
    
    predictions = model(input_eval)

    
    predictions = tf.squeeze(predictions, 0)
    predictions = predictions / temperature
    predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

    
    input_eval = tf.expand_dims([predicted_id], 0)

    text_generated.append(idx2char[predicted_id])
  
  return (start_string + ''.join(text_generated))

In [57]:
print(generate_text(model, start_string='I love Deep Learning: '))

I love Deep Learning: I heaving back in Scame
She's not that this want me that just a queen
In between 'em, yeah
To you dow think That you can trust is just
Another way to die How
And Mive you know you never loveds someone
The way that I lever for you You? I wanna hold my pillow
I wanna hold you Don't wanna go all night
Can treak Pary, it's a real man, yah, yeah, yeah And you no
Yeah, yeah, yeah, yeah)
Say yeah yeah yeah yeah
(Yeah, yeah, yeah, yeah)
Say yeah yeah yeah yeah
(Yeah, yeah, yeah, yeah)
Say yeah yeah yeah yeah
(Yeah, yeah, yeah, yeah, yeah)
Yeah Have you ever fert to here
It har I nut do somethingh world of me I'll get in the way of what I'm feeling
No one no onen's not
I paid touverthing was go
And let some other Jane Doe
Come, I and I con't tell your secrets
Your secrets are safe with me
I will keep your secrets
Just think of me as the pages in your diary (I here
Its all make it you, I love my name in my baby)
Tring my my just Another blin
What some people search for a fo